name: Multiple Job Lab
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building Application
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: 1.0.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Step
        run: |
          echo "ğŸ—ï¸ Building the application..."
          echo "Build completed successfully! $BUILD_VERSION"
      - name: Build Status
        if : success()
        run : echo "Build Succed"
      - name: Handle Failure
        if : failure()
        run: echo "Build faild.Please  check the logs"
  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Run tests
        run : |
          echo "ğŸ§ª Running tests..."
          echo "All tests passed!"
  deploy:
    name: Deploy Application
    needs: [build,test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        run: |
          echo "ğŸš€ Deploying application..."
          echo "Deployment successful!"

  notify:
    name: Send Notification
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Send Notofication
      run: |
          echo "ğŸ“§ Sending deployment notification..."
          echo "Notification sent!"